CREATE TABLE IF NOT EXISTS public.sigtap_procedures (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE public.sigtap_procedures ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to sigtap_procedures" 
ON public.sigtap_procedures FOR SELECT USING (true);

-- Inserindo alguns dados de exemplo (procedimentos comuns)
INSERT INTO public.sigtap_procedures (code, name) VALUES 
('0408050012', 'ARTROPLASTIA TOTAL DO QUADRIL'),
('0408050055', 'ARTROPLASTIA TOTAL DO JOELHO'),
('0415020050', 'COLECISTECTOMIA VIDEOLAPAROSCOPICA'),
('0406010072', 'APENDICECTOMIA'),
('0409010189', 'NEFROLITOTOMIA PERCUTANEA'),
('0408030011', 'REDUCAO INCRUENTA DE FRATURA DE FEMUR'),
('0408040050', 'TRATAMENTO CIRURGICO DE FRATURA DO COLO DO FEMUR'),
('0403010101', 'HERNIOPLASTIA INGUINAL (UNILATERAL)')
ON CONFLICT (code) DO NOTHING;
